server:
  port: 8189
spring:
  application:
    name: smartHomeController
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./database;MODE=PostgreSQL
    username: sa
    password:
    jpa:
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
    h2:
      console:
        enabled: true
        settings:
          web-allow-others: false
